### ISSUE TITLE
Tables are assigned by reference, not by value (related to copying tables)

### ISSUE THREAD

**Issue by pgaudiano** [NetLogo/Table-Extension#11]
This is not a bug or issue, as much as an aspect of tables that I have not seen described elsewhere, and should be mentioned in the description.

The 'set' operator handles tables by reference, whereas it treats regular variables and lists by value. This results in unexpected behavior.  

I am attaching a netlogo file that describes the issue in detail and shows a detailed set of examples. It also includes two simple procedures: copy-to-table and copy-to-clean-table, which make an item-by-item copy between tables. As the name should imply, the second version clears the target table before copying the contents of the source table.

It would be nice to explain this in the README and in the NetLogo manual. Also, it would be nice to create primitives that do the copying operations.

[table-copy-nlogo.txt](https://github.com/NetLogo/Table-Extension/files/2363473/table-copy-nlogo.txt)

**Comment by LaCuneta** [comment]
@pgaudiano Thanks for filing the issue and providing the samples!  There was some text about mutability under the **When to Use** section, but I agree with you that there needed to be more explicit documentation about what that means along with some examples.  I added a more elaborate explanation info under **Manipulating Tables** along with an example procedure to copy a table as a reference.
