### ISSUE TITLE
Add table:get-or-default

### ISSUE THREAD

**Issue by qiemem** [NetLogo/Table-Extension#2]
```
table:get-or-default <table> <key> <default-value>
```

Equivalent to:

```
ifelse-value (table:has-key? <table> <key>) [ table:get <table> <key> ] [ <defualt-value> ]
```

**Comment by SethTisue** [comment]
would default-value be lazily evaluated? if so, it should probably have square brackets around it, for consistency with the rest of the language

**Comment by qiemem** [comment]
I was imagining being eager (for simplicity). The choice of `get-or-default` rather than `get-or-else` was meant to convey that the argument should be a value.

That said, taking a task (bonus key as an argument) is a good alternative. `get-or-else` might be a better name in that case.

Advantage of eagerly evaluated value: simpler syntax. Advantage of task: laziness, default can easily be based off key.
